default:
  view:
    edit_profile:
      icon_size: 20
max_file_size: 5
default_avatar: "profile_avatar.png"
allowed_image_file_type: ["image/png", "image/jpg", "image/jpeg", "image/gif"]
phone_number_regex: "\\A(\\+\\d{1,3}[- ]?)?\\d{10}\\z"
recommend_users_limit: 5
